source "https://rubygems.org"

source 'https://rubygems.org'

gem 'jekyll', '~> 4.4.1'
gem 'minima'
gem 'jekyll-seo-tag'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-paginate'
gem "jekyll-theme-minimal"

